name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: UnitTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        working-directory: ./reef-monitor-react-app
        run: npm ci
      - name: UnitTest
        working-directory: ./reef-monitor-react-app
        run: npm test