name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test using unit test
      uses: actions/setup-node@v1
      working-directory: ./reef-monitor-react-app
      with:
        node-version: '12'
      run: npm install
    - run: npm test