name: Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        working-directory: ./reef-monitor-react-app
        run: npm ci
      - name: Prettier
        working-directory: ./reef-monitor-react-app
        run: npm run format
      - name: Lint
        working-directory: ./reef-monitor-react-app
        run: npm run lint